//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssertManagementRepository.AssertModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetUserMappings = new HashSet<AssetUserMapping>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter Asset Name")]
        public string AssetName { get; set; }
        public int CategoryId { get; set; }
        
        public int BrandId { get; set; }
        [Required(ErrorMessage = "Enter available count")]
        [Range(1,int.MaxValue)]
        public int AvailableCount { get; set; }
        [Required(ErrorMessage = "Enter total count")]
        public int TotalCount { get; set; }
        [Required(ErrorMessage = "Select warenty end date")]
        public Nullable<System.DateTime> WarrentyEndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetUserMapping> AssetUserMappings { get; set; }
    }
}
