//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuestionnaireApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDetail
    {
        public int ResultId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.TimeSpan> TimeTaken { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
