//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int BookId { get; set; }
        [Required(ErrorMessage = "*Enter your book name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "*Enter the author name")]
        public string Author { get; set; }
        [Required(ErrorMessage = "*Enter the price")]
        [Range(0, double.MaxValue, ErrorMessage = "*Please enter valid Price")]
        public double Price { get; set; }
    }
}
